trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnectionName: 'AzureServiceConnection'
  location: 'West Europe'
  resourceGroupName: 'example-resources-001-test'
  storageAccountName: 'examplestorageacct'
  containerName: 'tfstate'
  tfStateKey: 'terraform.tfstate'

steps:
- task: UseTerraform@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: $(serviceConnectionName)
  displayName: 'Terraform Init for Main Infra'

- task: UseTerraform@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: $(serviceConnectionName)
    additionalArgs: '-var "location=$(location)" -var "resource_group_name=$(resourceGroupName)"'
  displayName: 'Terraform Plan for Main Infra'

- task: UseTerraform@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: $(serviceConnectionName)
    additionalArgs: '-auto-approve -var "location=$(location)" -var "resource_group_name=$(resourceGroupName)"'
  displayName: 'Terraform Apply for Main Infra'
